spring:
   data:
      mongodb:
         #Connecting to Replica set
         uri: mongodb://localhost:27017,localhost:27018,localhost:27019/test_db?replSetName=repl1
         #uri: mongodb://127.0.0.1:27017/test_db
   