spring:
   data:
      mongodb:
         uri: mongodb+srv://admin:admin@cluster0.gei86.mongodb.net/test_db?retryWrites=true&w=majority
         #host: localhost
         #port: 27017
         #database: test_db



